name: CI

on:
  pull_request:
    paths-ignore: ["**.md"]
  push:
    branches: ["main"]
    paths-ignore: ["**.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node@${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Install Playwright
        run: npx playwright install-deps chromium
      - name: Run tests
        run: npm run ci:test
      - name: Report code coverage
        uses: codecov/codecov-action@v2
